[package]
name = "autocrypt"
version = "0.1.0"
description = "Rust implmentation of https://autocrypt.org"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
quick-error = "^1.2.0"
email = "*"
time = "*"
